//! Golden-vector parity: the Rust core must reproduce the *actual* web gold
//! master's DSP output (fixtures generated by `tests/golden/gen-golden.mjs` from
//! the verbatim functions in `app/index.html`).
//!
//! The short signal is dumped in the fixture so the spectral comparison uses an
//! identical input; the long signal is regenerated here by the same closed-form
//! expression used in the harness (so tempo parity needs no 3 MB input dump).

use std::path::PathBuf;

use serde_json::Value;
use stemacle_dsp::stft::{hann, stft, FFT_SIZE, SR};
use stemacle_dsp::{estimate_tempo, LoopGrid};

fn load_fixture() -> Value {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../../fixtures/golden/dsp-golden.json");
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("read {}: {e}\nrun: node tests/golden/gen-golden.mjs", path.display()));
    serde_json::from_str(&text).expect("parse golden json")
}

/// Long signal mirrored from `longSignal` in the harness (single expression per
/// sample → identical f64→f32 rounding).
fn long_signal(n: usize) -> Vec<f32> {
    let period = (0.5 * SR as f64).round() as usize; // 120 BPM
    (0..n)
        .map(|i| {
            let t = i as f64 / SR as f64;
            let phase = i % period;
            let click = if phase < 300 { (1.0 - phase as f64 / 300.0) * 0.5 } else { 0.0 };
            ((2.0 * std::f64::consts::PI * 220.0 * t).sin() * 0.25 + click) as f32
        })
        .collect()
}

#[test]
fn stft_matches_gold_master() {
    let fx = load_fixture();
    let short: Vec<f32> = fx["shortSignal"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_f64().unwrap() as f32)
        .collect();

    let spec = stft(&short, &hann(FFT_SIZE));
    for frame in fx["stft"].as_array().unwrap() {
        let f = frame["frame"].as_u64().unwrap() as usize;
        for bin in frame["bins"].as_array().unwrap() {
            let b = bin["b"].as_u64().unwrap() as usize;
            let re_js = bin["re"].as_f64().unwrap() as f32;
            let im_js = bin["im"].as_f64().unwrap() as f32;
            // Allow f32-vs-f64-twiddle drift; tight enough to catch real bugs.
            let tol = |x: f32| 1e-2 + 1e-3 * x.abs();
            assert!(
                (spec.re[f][b] - re_js).abs() <= tol(re_js),
                "stft re mismatch frame {f} bin {b}: {} vs {}",
                spec.re[f][b], re_js
            );
            assert!(
                (spec.im[f][b] - im_js).abs() <= tol(im_js),
                "stft im mismatch frame {f} bin {b}: {} vs {}",
                spec.im[f][b], im_js
            );
        }
    }
}

#[test]
fn hann_matches_gold_master() {
    let fx = load_fixture();
    let w = hann(FFT_SIZE);
    let vals = fx["hannSamples"]["values"].as_array().unwrap();
    for (k, idx) in [1usize, 1024, 2048, 3072].into_iter().enumerate() {
        let js = vals[k].as_f64().unwrap() as f32;
        assert!((w[idx] - js).abs() < 1e-6, "hann[{idx}] {} vs {}", w[idx], js);
    }
}

#[test]
fn tempo_matches_gold_master() {
    let fx = load_fixture();
    let n = fx["tempo"]["n"].as_u64().unwrap() as usize;
    let sig = long_signal(n);
    let est = estimate_tempo(&sig, SR as f32);

    let bpm_js = fx["tempo"]["bpm"].as_f64().unwrap() as f32;
    let meas_js = fx["tempo"]["measureOffset"].as_f64().unwrap() as f32;
    let beat_js = fx["tempo"]["beatOffset"].as_f64().unwrap() as f32;

    assert!((est.bpm - bpm_js).abs() < 0.5, "bpm {} vs {}", est.bpm, bpm_js);
    // offsets are quantized to a 10ms hop; allow a couple hops of drift.
    assert!((est.measure_offset - meas_js).abs() < 0.03, "measureOffset {} vs {}", est.measure_offset, meas_js);
    assert!((est.beat_offset - beat_js).abs() < 0.03, "beatOffset {} vs {}", est.beat_offset, beat_js);
}

#[test]
fn loop_math_matches_gold_master() {
    let fx = load_fixture();
    // Fixture loop state: bpm 120, offsets 0, duration 60 (see harness).
    let grid = LoopGrid { bpm: 120.0, measure_offset: 0.0, beat_offset: 0.0, duration: 60.0 };
    for case in fx["loops"].as_array().unwrap() {
        let cur = case["currentSec"].as_f64().unwrap() as f32;
        let len = case["loopLength"].as_f64().unwrap() as f32;
        let end_js = case["end"].as_f64().unwrap() as f32;
        let start_js = case["range"]["start"].as_f64().unwrap() as f32;
        let range_end_js = case["range"]["end"].as_f64().unwrap() as f32;

        assert!((grid.snap_loop_end(cur, len) - end_js).abs() < 1e-4, "snapLoopEnd cur={cur}");
        let (start, end) = grid.loop_range_for(cur, len);
        assert!((start - start_js).abs() < 1e-4, "loopRange start cur={cur}");
        assert!((end - range_end_js).abs() < 1e-4, "loopRange end cur={cur}");
    }
}
